[project]
name = "fontbench-web"
version = "0.1.0"
description = "Web app for visualizing and inspecting FontBench results"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.0,<0.129.0",
    "fontbench",
    "glyphslib>=6.12.6",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pillow>=12.1.0",
    "pyvips>=3.1.1",
    "sqlalchemy>=2.0.46",
]

[project.scripts]
fontbench-web = "app.main:run_server"

[tool.uv.sources]
fontbench = { git = "https://github.com/georgeyjm/fontbench.git" }
