name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/apps/fontbench-web
            git pull origin main
            uv sync
            sudo ln -sf $(pwd)/deploy/fontbench.georgeyjm.com.service /etc/systemd/system/fontbench.georgeyjm.com.service
            sudo systemctl daemon-reload
            sudo systemctl restart fontbench.georgeyjm.com
